/*
MySQL Backup
Database: zentao
Backup Time: 2020-02-12 12:18:58
*/

SET FOREIGN_KEY_CHECKS=0;
DROP VIEW IF EXISTS `zentao`.`ztv_usercurrentbug`;
DROP VIEW IF EXISTS `zentao`.`ztv_usercurrenttask`;
DROP VIEW IF EXISTS `zentao`.`ztv_userdayactivebug`;
DROP VIEW IF EXISTS `zentao`.`ztv_userdayclosebug`;
DROP VIEW IF EXISTS `zentao`.`ztv_userdaydotask`;
DROP VIEW IF EXISTS `zentao`.`ztv_userdayopenbug`;
DROP VIEW IF EXISTS `zentao`.`ztv_userdayresolvebug`;
CREATE ALGORITHM=UNDEFINED DEFINER=``@`` SQL SECURITY DEFINER VIEW `ztv_usercurrentbug` AS select `zt_bug`.`assignedTo` AS `account`,`zt_user`.`realname` AS `realname`,`zt_lang`.`value` AS `severity`,count(0) AS `bugassign`,group_concat(concat('#',`zt_bug`.`id`,`zt_bug`.`title`) separator '<br />') AS `bugs` from ((`zt_bug` join `zt_user` on((`zt_user`.`account` = `zt_bug`.`assignedTo`))) join `zt_lang` on(((`zt_bug`.`severity` = `zt_lang`.`key`) and (`zt_lang`.`lang` = 'zh-cn') and (`zt_lang`.`module` = 'bug') and (`zt_lang`.`section` = 'severityList')))) where ((`zt_bug`.`deleted` = '0') and (`zt_bug`.`assignedTo` <> 'closed')) group by `zt_bug`.`assignedTo`,`zt_bug`.`severity`;
CREATE ALGORITHM=UNDEFINED DEFINER=``@`` SQL SECURITY DEFINER VIEW `ztv_usercurrenttask` AS select `zt_task`.`assignedTo` AS `account`,`zt_user`.`realname` AS `realname`,`zt_task`.`status` AS `status`,count(0) AS `taskassign`,group_concat(concat('#',`zt_task`.`id`,`zt_task`.`name`) separator '<br />') AS `tasks` from (`zt_task` join `zt_user` on((`zt_user`.`account` = `zt_task`.`assignedTo`))) where ((`zt_task`.`deleted` = '0') and (`zt_task`.`status` <> 'closed')) group by `zt_task`.`assignedTo`,`zt_task`.`status`;
CREATE ALGORITHM=UNDEFINED DEFINER=``@`` SQL SECURITY DEFINER VIEW `ztv_userdayactivebug` AS select `zt_user`.`account` AS `account`,`zt_user`.`realname` AS `realname`,left(`zt_action`.`date`,10) AS `day`,`zt_lang`.`value` AS `severity`,count(0) AS `bugactive`,group_concat(concat('#',`zt_bug`.`id`,`zt_bug`.`title`) separator '<br />') AS `bugs` from (((`zt_action` join `zt_user` on((`zt_user`.`account` = `zt_action`.`actor`))) join `zt_bug` on((`zt_bug`.`id` = `zt_action`.`objectID`))) join `zt_lang` on(((`zt_bug`.`severity` = `zt_lang`.`key`) and (`zt_lang`.`lang` = 'zh-cn') and (`zt_lang`.`module` = 'bug') and (`zt_lang`.`section` = 'severityList')))) where ((`zt_action`.`objectType` = 'bug') and (`zt_action`.`action` = 'activated')) group by `zt_action`.`actor`,left(`zt_action`.`date`,10),`zt_bug`.`severity`;
CREATE ALGORITHM=UNDEFINED DEFINER=``@`` SQL SECURITY DEFINER VIEW `ztv_userdayclosebug` AS select `zt_bug`.`closedBy` AS `account`,`zt_user`.`realname` AS `realname`,left(`zt_bug`.`closedDate`,10) AS `day`,`zt_lang`.`value` AS `severity`,count(0) AS `bugclose`,group_concat(concat('#',`zt_bug`.`id`,`zt_bug`.`title`) separator '<br />') AS `bugs` from ((`zt_bug` join `zt_user` on((`zt_user`.`account` = `zt_bug`.`closedBy`))) join `zt_lang` on(((`zt_bug`.`severity` = `zt_lang`.`key`) and (`zt_lang`.`lang` = 'zh-cn') and (`zt_lang`.`module` = 'bug') and (`zt_lang`.`section` = 'severityList')))) where (`zt_bug`.`deleted` = '0') group by `zt_bug`.`closedBy`,left(`zt_bug`.`closedDate`,10),`zt_bug`.`severity`;
CREATE ALGORITHM=UNDEFINED DEFINER=``@`` SQL SECURITY DEFINER VIEW `ztv_userdaydotask` AS select `zt_taskestimate`.`account` AS `account`,`zt_user`.`realname` AS `realname`,date_format(`zt_taskestimate`.`date`,'%Y-%m-%d') AS `day`,`zt_taskestimate`.`task` AS `taskid`,`zt_task`.`name` AS `taskname`,round(sum(`zt_taskestimate`.`consumed`),2) AS `consumed`,round(`zt_task`.`estimate`,2) AS `estimate`,round(`zt_task`.`left`,2) AS `left` from ((`zt_taskestimate` join `zt_user` on((`zt_user`.`account` = `zt_taskestimate`.`account`))) join `zt_task` on((`zt_taskestimate`.`task` = `zt_task`.`id`))) group by `zt_taskestimate`.`account`,`zt_taskestimate`.`date`,`zt_taskestimate`.`task`;
CREATE ALGORITHM=UNDEFINED DEFINER=``@`` SQL SECURITY DEFINER VIEW `ztv_userdayopenbug` AS select `zt_bug`.`openedBy` AS `account`,`zt_user`.`realname` AS `realname`,left(`zt_bug`.`openedDate`,10) AS `day`,`zt_lang`.`value` AS `severity`,count(0) AS `bugopen`,group_concat(concat('#',`zt_bug`.`id`,`zt_bug`.`title`) separator '<br />') AS `bugs` from ((`zt_bug` join `zt_user` on((`zt_user`.`account` = `zt_bug`.`openedBy`))) join `zt_lang` on(((`zt_bug`.`severity` = `zt_lang`.`key`) and (`zt_lang`.`lang` = 'zh-cn') and (`zt_lang`.`module` = 'bug') and (`zt_lang`.`section` = 'severityList')))) where (`zt_bug`.`deleted` = '0') group by `zt_bug`.`openedBy`,left(`zt_bug`.`openedDate`,10),`zt_bug`.`severity`;
CREATE ALGORITHM=UNDEFINED DEFINER=``@`` SQL SECURITY DEFINER VIEW `ztv_userdayresolvebug` AS select `zt_bug`.`resolvedBy` AS `account`,`zt_user`.`realname` AS `realname`,left(`zt_bug`.`resolvedDate`,10) AS `day`,`zt_lang`.`value` AS `severity`,count(0) AS `bugresolve`,group_concat(concat('#',`zt_bug`.`id`,`zt_bug`.`title`) separator '<br />') AS `bugs` from ((`zt_bug` join `zt_user` on((`zt_user`.`account` = `zt_bug`.`resolvedBy`))) join `zt_lang` on(((`zt_bug`.`severity` = `zt_lang`.`key`) and (`zt_lang`.`lang` = 'zh-cn') and (`zt_lang`.`module` = 'bug') and (`zt_lang`.`section` = 'severityList')))) where (`zt_bug`.`deleted` = '0') group by `zt_bug`.`resolvedBy`,left(`zt_bug`.`resolvedDate`,10),`zt_bug`.`severity`;
